### ISSUE TITLE
"notificationResponse" not firing when app is opened from a notification?

### ISSUE THREAD

**Issue by Zyphxion** [urbanairship/react-native-module#23]
Maybe I'm going about this the wrong way, but after reading [this migration guide](https://github.com/urbanairship/react-native-module/blob/master/ReactNativeUAMigration.md) it looks like "notificationResponse" should have the same functionality as "launchedFromNotification," however when launching my app from a notification nothing is happening.  All I have in the event is a simple alert, set up the exact same way as the sample project, inside the componentWillMount lifecycle step.

Could there be something I'm missing?  My goal is to have a user open the app via a notification and upon entering the application see an alert that has a message and a few other things from the "extras" field.  I even tried including the message and extra data in the "in_app" attribute in the push object being sent to UA from my server, no dice.

Thanks in advance.

**Comment by rlepinski** [comment]
@Zyphxion what platform OS version? Can you reproduce your issue with the sample?

**Comment by rlepinski** [comment]
Closing for now. If you are still having an issue please reopen with the requested info.

**Comment by surendharreddy** [comment]
@ralepinski this happens for me. I can reproduce it on my side after migrating from `react-native-ua`. 

Implemented it same as @Zyphxion. When launching the app from the notification I don't see my alerts getting triggered. 

I'm using `"urbanairship-react-native": "^2.0.1"` with `"react-native": "0.55.4"`.

**Comment by BrianBatchelder** [comment]
Thanks for the report, @Zyphxion . We will take a look at this. In the meantime, we released version 2.0.2 yesterday. I’m not sure it will address your issue, but you might give it a try.

**Comment by surendharreddy** [comment]
Thanks for reopening this @BrianBatchelder. Look forward to the fix. Let me know if you need any additional details, I would be happy to provide them.

**Comment by BrianBatchelder** [comment]
@surendharreddy: could you try version 2.0.2 and let me know if your issue still exists? I meant to ask you in my previous comment, but copied and pasted the wron user name. Thanks.

**Comment by surendharreddy** [comment]
@BrianBatchelder I tried using version 2.0.2 and the issue still exits. 😞

**Comment by BrianBatchelder** [comment]
@surendharreddy: the migration guide says: 

> UrbanAirship.addListener(eventName: string, listener: Function) requires specifying the event name when adding the `listener. 

Are you calling `addListener` for the `notificationResponse` event?

**Comment by surendharreddy** [comment]
Yes, I'm calling `addListener` for the 'notificationResponse'. That's how it's firing when the app is in the active or background state. I'm only unable to fire it when the app is launched with notification.

**Comment by BrianBatchelder** [comment]
@surendharreddy : We are actively working on this and hope to have more information soon.

**Comment by surendharreddy** [comment]
Thanks, @crow @BrianBatchelder for the help. Will use the updated code once the PR is merged.

**Comment by Canedo** [comment]
We are facing the same issue here. Android and iOS. Is there any news on this issue?

**Comment by BrianBatchelder** [comment]
@surendharreddy @Canedo : Version 2.1.0 has been released, and should address your issue. Please give it a try and let us know if it works for you.

**Comment by Canedo** [comment]
@BrianBatchelder Hello! Is it not been released on npm, right?

**Comment by crow** [comment]
@Canedo just [released to npm](https://www.npmjs.com/package/urbanairship-react-native)

**Comment by Canedo** [comment]
I'm facing an issue building this release.

```
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForG1Debug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
```
I think it could be related to upgrading firebase-core from 16.0.1 to 16.0.3.

I saw a similar issue [here](https://github.com/invertase/react-native-firebase/issues/1051)

**Comment by Canedo** [comment]
I can force back to 16.0.1. Android is working like a charm. I'll try to test on iOS asap but very likely it's gonna be on monday.

**Comment by Canedo** [comment]
Do we need to upgrade UrbanAirship-iOS-SDK and UrbanAirship-iOS-AppExtensions to 10.0.0?

**Comment by rlepinski** [comment]
Yes, its required for the new enable notifications method. I wish we had a better way of forcing that other than the readme and log message.

**Comment by Canedo** [comment]
Not a problem. I don't think we will have many issues handling this major update.

**Comment by Canedo** [comment]
Hey @rlepinski 

```
Showing All Messages
.../ios/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common/UAAPNSRegistration.m:42:38: Property 'criticalAlertSetting' not found on object of type 'UNNotificationSettings *'
.../ios/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common/UAAPNSRegistration.m:54:23: Use of undeclared identifier 'UNAuthorizationStatusProvisional'; did you mean 'UAAuthorizationStatusProvisional'?
.../ios/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common/UAAPNSRegistration.m:93:26: Use of undeclared identifier 'UNAuthorizationOptionCriticalAlert'; did you mean 'UANotificationOptionCriticalAlert'?
.../ios/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common/UAAPNSRegistration.m:97:26: Use of undeclared identifier 'UNAuthorizationOptionProvidesAppNotificationSettings'; did you mean 'UANotificationOptionProvidesAppNotificationSettings'?
.../ios/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common/UAAPNSRegistration.m:101:26: Use of undeclared identifier 'UNAuthorizationOptionProvisional'
```
I have found UAAuthorizationStatusProvisional, UANotificationOptionCriticalAlert and UANotificationOptionProvidesAppNotificationSettings into the ios project. maybe is this a typo error on the 10.0.0 version?

**Comment by rlepinski** [comment]
@Canedo You also need to use the Xcode 10. This release supports new features for iOS 12

**Comment by surendharreddy** [comment]
Thanks @BrianBatchelder for the update. I'll test the latest version during this week and let you know.

**Comment by surendharreddy** [comment]
Getting some new issues after installing the latest version. 

1. Updated npm module version to 2.1.0
2. Updated Urban Airship SDK to 10 (Installed with Cocoapods)

![screen shot 2018-09-27 at 12 48 29 pm](https://user-images.githubusercontent.com/7141644/46123956-d5369b80-c253-11e8-99e5-9f16ad891348.png)

Getting an error ar https://github.com/urbanairship/react-native-module/blob/master/ios/UARCTModule/UrbanAirshipReactModule.m#L71

![screen shot 2018-09-27 at 12 38 50 pm](https://user-images.githubusercontent.com/7141644/46123960-d667c880-c253-11e8-8f06-2b4234b0ed87.png)

Not sure why this is happening. Reverting back to older versions all results in build failures now.

**Comment by surendharreddy** [comment]
Reverting back to 2.0.2 was breaking because the wrong version was getting installed (something issue related to my `package-lock.json`). 

I suspect this error `No visible @interface for 'UAPush' declares the selector 'enableUserPushNotifications:'` is because the latest Urban Airship SDK (version >= 10) is not getting installed properly?

**Comment by rlepinski** [comment]
@surendharreddy Its public in [SDK v10.0]([url](https://github.com/urbanairship/ios-library/blob/master/AirshipKit/AirshipKit/common/UAPush.h#L435)).Double check that you are installing the SDK and updated your pod.

**Comment by surendharreddy** [comment]
Thanks, @rlepinski, and @BrianBatchelder for the help. Now it's working fine on both iOS and Android. 

Although I kinda felt version 2.1.0 is not optimistic update. It needs XCode 10 which has a major bug when using the new build system (Xcode build fails to download third-party dependencies) which is selected by default. It took me some time to realize and use legacy build system (from workspace settings) to actually build the app without any errors. 

Here are some observations from my experience in upgrading to the latest version. 

1. Using XCode 10 on React Native apps fails to download third-party dependencies. To resolve this, we need to use old legacy build system which is available from workspace settings. 
2. We need to change the iOS app deployment target to 10 in podfile. Without this, the `pod update` will always show the latest version of UrbanAirship-iOS-SDK to something below 10.0.0. 
3. Android build throws an error `Error while generating the main dex` when building which @Canedo reported already. This can be solved by changing firebase-core from 16.0.3 to 16.0.1 (compile 'com.google.firebase:firebase-core:16.0.1') in module itself (android/build.gradle)

Let me know if there's any way I can add these notes to Urban Airship documentation. So other developers won't have the trouble later.

**Comment by rlepinski** [comment]
@surendharreddy Thanks for the feedback. We can address the Android issue in the next release but in order to use the latest features we wont be able to change our hard dependency with Xcode 10.

Could you explain 1 in more detail? When you say downloading 3rd party dependencies are you referring to cocoapods? Do you have a bug you can point me to?

**Comment by surendharreddy** [comment]
@ralepinski the issue was not with cocoapods but with all other React Native dependencies. 

Here are the few issues I ran into when using XCode 10. 
- https://github.com/facebook/react-native/issues/19569
- https://github.com/facebook/react-native/issues/20774

Hope it helps. I would be happy to assist you with any details.

**Comment by surendharreddy** [comment]
Thanks, @crow for the fix. Now Android build is working fine. 👌🏻

**Comment by rlepinski** [comment]
We released 2.1.1 with the Android fix, and also 2.0.3 that includes this fix but does not requires Xcode 10 (UA SDK 10).
